baseURL: https://themennonite-historyproject.netlify.app
title: MHP
theme: meghna-hugo
paginate: '6'
summaryLength: '15'
disqusShortname: 'https-themennonitehistoryproject-netlify-app'
disableLanguages: []
params:
  author: Themefisher
  cookies:
    enable: no
    expire_days: 2
  description: Responsive Multipurpose Parallax Hugo Template
  google_analytics_id: ''
  logo: images/logo.png
  map:
    enable: no
    gmap_api: https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ
    map_latitude: '51.5223477'
    map_longitude: '-0.1622023'
    map_marker: images/marker.png
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/themify-icons/themify-icons.css
      - link: plugins/magnific-popup/magnific-popup.css
      - link: plugins/slick/slick.css
      - link: https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap
    js:
      - link: plugins/jquery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/magnific-popup/jquery.magnific-popup.min.js
      - link: plugins/lazy-load/lozad.min.js
      - link: plugins/google-map/map.js
  post_share: no
  preloader:
    enable: yes
    preloader: images/logo.png
  social:
    - icon: ti-youtube
      link: 'https://www.youtube.com/user/colef'

Languages:
  en:
    contentDir: content/english
    copyright: Research conducted at [El Colegio de la Frontera Norte]( https://www.colef.mx/). Analysis and opinions expressed are the authors responsibility and does not necessarily reflect an institutional position on the matter. Copyright &copy; 2021 Web theme designed by [Themefisher](https://themefisher.com).All graphic materials used in this academic presentation are intended for educational purposes only and are used under a total non for profit research setting.
    home: Home
    languageCode: en-us
    languageName: En
    menu:
      main:
        - name: Methods  
          url: '#about'
          weight: 1
        - name: Structure
          url: '#services'
          weight: 2
        - name: Main crops
          url: '#portfolio'
          weight: 3
        - name: Church Brethren
          url: '#team'
          weight: 4
        - name: Chapters
          url: '#blog'
          weight: 5
        - name: Let's collaborate
          url: '#contact'
          weight: 6
        - name: Get full PDF 
          url: https://migracionesinternacionales.colef.mx/index.php/migracionesinternacionales/article/view/1920/1608
          weight: 7
        - name: About 
          url: https://joseluismanzanaresrivera.github.io/profile/index.html
          weight: 8